doctrine:
  dbal:
    types:
      carbon: 'App\SharedContext\Infrastructure\Persistence\Doctrine\Type\CarbonType'
      cheat_meal_id: 'App\IndContext\CheatMealModule\Infrastructure\Persistence\Doctrine\Type\CheatMealIdType'
      meal_id: 'App\IndContext\MealModule\Infrastructure\Persistence\Doctrine\Type\MealIdType'
      meal_template_id: 'App\IndContext\MealModule\Infrastructure\Persistence\Doctrine\Type\MealTemplateIdType'
      schedule_id: 'App\IndContext\SharedModule\Infrastructure\Persistence\Doctrine\Type\ScheduleIdType'
    default_connection: default
    connections:
      default:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_mysql'

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'
  orm:
    auto_generate_proxy_classes: true
    default_entity_manager: default

    entity_managers:
      default:
        connection: default
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
          App\Indcontext\CheatMealModule:
            is_bundle: false
            alias: IndContext_CheatMealModule
            type: xml
            prefix: 'App\IndContext\CheatMealModule\Domain'
            dir: '%kernel.project_dir%/src/IndContext/CheatMealModule/Infrastructure/Persistence/Doctrine/Mapping'

          App\IndContext\MealModule:
            is_bundle: false
            alias: IndContext_MealModule
            type: xml
            prefix: 'App\IndContext\MealModule\Domain'
            dir: '%kernel.project_dir%/src/IndContext/MealModule/Infrastructure/Persistence/Doctrine/Mapping'

          App\IndContext\SharedModule:
            is_bundle: false
            alias: IndContext_SharedModule
            type: xml
            prefix: 'App\IndContext\SharedModule\Domain'
            dir: '%kernel.project_dir%/src/IndContext/SharedModule/Infrastructure/Persistence/Doctrine/Mapping'

          App\IndContext\WorkoutModule:
            is_bundle: false
            alias: IndContext_WorkoutModule
            type: xml
            prefix: 'App\IndContext\WorkoutModule\Domain'
            dir: '%kernel.project_dir%/src/IndContext/WorkoutModule/Infrastructure/Persistence/Doctrine/Mapping'
