services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '%kernel.project_dir%/src/'
    exclude:
      - '%kernel.project_dir%/src/DependencyInjection/'
      - '%kernel.project_dir%/src/Entity/'
      - '%kernel.project_dir%/src/SharedContext/Infrastructure/Symfony/Kernel.php'
      - '%kernel.project_dir%/src/Tests/'

  controllers:
    namespace: App\
    resource: '%kernel.project_dir%/src/*Context/Infrastructure/Controller/**/'
    tags: [ 'controller.service_arguments' ]

  tactician_handlers:
    namespace: App\*Context\Application\Command\
    resource: '%kernel.project_dir%/src/*Context/Application/Command/**/*Handler.php'
    tags:
      - { name: tactician.handler, typehints: true }

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
