services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '%kernel.project_dir%/src/'
    exclude:
      - '%kernel.project_dir%/src/DependencyInjection/'
      - '%kernel.project_dir%/src/Entity/'
      - '%kernel.project_dir%/src/SharedContext/Infrastructure/Symfony/Kernel.php'
      - '%kernel.project_dir%/src/Tests/'


  tactician_command_handlers:
    namespace: App\
    resource: '%kernel.project_dir%/src/*Context/*Module/Application/Command/**/*Handler.php'
    tags:
      - { name: tactician.handler, typehints: true }

  tactician_query_handlers:
    namespace: App\
    resource: '%kernel.project_dir%/src/*Context/*Module/Application/Query/**/*Handler.php'
    tags:
      - { name: tactician.handler, typehints: true }

  App\SharedContext\Infrastructure\Bus\TacticianCommandBus:
    public: false
    arguments:
      - '@tactician.commandbus'

  controllers:
    namespace: App\
    resource: "../src/**/Infrastructure/Controller/"
    tags: [ 'controller.service_arguments' ]
